### PR TITLE
Streamline login

### PR DESCRIPTION
**Pull request by dickmao**
Merge the login and open commands (open aliased to login).  Add login
tests described in #352.

Attempt to improve user experience by synchronously executing
`ein:jupyter-server-start`.  `ein:dev-prefer-deferred` custom variable
allows easy switch to compare synchronous versus old asynchronous behavior.

### CODE REVIEW

**Comment by millejoh** [comment]
It may be passing on travis, but I'm running into issues on my dev machine. First, even though I call `M-x ein:jupyter-server-stop`, EIN still complains that I haven't executed `M-x ein:jupyter-server-stop` when  I call `M-x ein:jupyter-server-start`. I have to manually delete the `*ein:jupyter-server*` buffer before this works.

Also, on calling `ein:jupyter-server-start` EIN has mysteriously lost the ability to find and use the authentication token. I see a "401 post /login" in the jupyter server log.

**Comment by millejoh** [comment]
Also, on my MSYS2 setup, when I call `make test` I get a message "Buffer is read only: `#<buffer ein-loaddefs.el>`" and later the build fails with various messages saying ein-loaddefs does not exist.

```
$ make test
cask clean-elc
sh tools/update-autoloads.sh
Buffer is read-only: #<buffer ein-loaddefs.el>
! ( cask build 2>&1 | awk '{if (/^ /) { gsub(/^ +/, " ", $0); printf "%s", $0 } else { printf "\n%s", $0 }}' | egrep "not known|Error|free variable" )
lisp/debug-ein.el:30:1:Error: Cannot open load file: No such file or directory, ein-loaddefs
lisp/ein-dev.el:31:1:Error: Cannot open load file: No such file or directory, ein-loaddefs
lisp/ein-ipynb-mode.el:29:1:Error: Cannot open load file: No such file or directory, ein-loaddefs
lisp/ein-jupyter.el:28:1:Error: Cannot open load file: No such file or directory, ein-loaddefs
lisp/ein-process.el:31:1:Error: Cannot open load file: No such file or directory, ein-loaddefs
```

**Comment by dickmao** [comment]
Please re-pull and see if things are different.  Thanks.

**Comment by dickmao** [comment]
Well, it shouldn't be too troubling.  It makes sense that a testing tool such as travis which does not offer a Windows option also cannot manifest problems on Windows.  If we ever get serious about testing all platforms, incorporating your exact msys2 env into `.appveyor.yml` would take some doing.

If there are circumstances under which a user wouldn't want to immediately `notebooklist-open` after `notebooklist-login`, or if the unification is simply something you don't want, that would be sufficient reason to close this PR.

The Windows misbehavior you describe might be something we could work through, although I'm not sure how.  I couldn't reproduce.

**Comment by millejoh** [comment]
Okay, I think I'm ready to stick a fork in this one. The issues I noted on remote connections seem to have disappeared, and everything else seems to be working mostly as it did before. I think I may even have a way to catch that case that tripped me up earlier, but only experience will tell.

If you know any technology deities, now might be a good time to send them a prayer. I'm going to merge and push this to github a little later this evening.

**Pull request merged**
