### PR TITLE
Dependency f.el

### LINKED ISSUE #395: unspecified dependency: 'f'
Installing ein succeeds but errors of the form:

`Error: Cannot open load file: No such file or directory, f`

appear many times in the `*Compile-Log*` buffer for different `.el` files. Furthermore, when I try to begin by using `M-x ein:notebook-open` (or several other basic initial commands) the same error is printed in the minibuffer.

Things I have tried:
- starting clean with `emacs -q`
- removing all `.elc` files from my install dir (`~/.emacs.d/...`)
- running `M-x ein:dev-bug-report-template` (fails with an error about markdown-mode, which is installed - unclear what the issue is)

Although I could not run the bug report template I was able to run `ein:dev-show-sys-info`, which produced this:

```elisp
("EIN system info" :emacs-version "GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.23.2)\n of 2018-08-27, modified by Debian" :emacs-bzr-version nil :window-system x :emacs-variant nil :os
 (:uname "Linux jet-Oryx-Pro 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\n" :lsb-release "No LSB modules are available.\nDistributor ID:	Ubuntu\nDescription:	Ubuntu 18.10\nRelease:	18.10\nCodename:	cosmic\n")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend url-retrieve)
 :ein
 (:version "0.15.0-20181106.1910" :source-dir "/home/jet/.emacs.d/elpa/ein-20181106.1910/")
 :lib
 ((:name "websocket" :path "~/.emacs.d/elpa/websocket-20180423.16/websocket.el" :featurep t :version-var websocket-version :version "1.9")
  (:name "request" :path "~/.emacs.d/elpa/request-20170201.147/request.el" :featurep t :version-var request-version :version "0.3.0")
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.el" :featurep t :version-var nil :version nil)
  (:name "auto-complete" :path "~/.emacs.d/elpa/auto-complete-20170125.245/auto-complete.el" :featurep t :version-var nil :version nil)
  (:name "popup" :path "~/.emacs.d/elpa/popup-20160709.1429/popup.elc" :featurep t :version-var popup-version :version "0.5.3")
  (:name "python" :path "/usr/share/emacs/25.2/lisp/progmodes/python.elc" :featurep t :version-var nil :version nil)))
```
I have attached [the compile log](https://github.com/millejoh/emacs-ipython-notebook/files/2560431/errors.txt) in case it helps.

### PR DESCRIPTION
**Pull request by dickmao**
Fixes #395 

Also, we are at a point where travis failures might actually indicate a real problem.  So if any ein contributors happen to read this message, please don't immediately dismiss a travis failure as a false positive.

### CODE REVIEW

**Comment by millejoh** [comment]
When was the dependency on f introduced? It certainly didn't happen with @sam-s's PR. Travis was failing because the notification message changed. I caught it in the unit test, but missed the ecukes scenario.

Also, for the ecukes scenario looks like I have to hard code the notification string, but the correct way would be to parse it through `(substitute-command-keys <string>)`.

Also, final note - while the name `ein:notebook-reconnect-session-command` may be slightly more descriptive of what is happening internally on the Jupyter server, the naming is inconsistent with the notebook browser interface. I added an alias for the old command, which I think should keep the amount of confusion, but in the future think long and hard before renaming user-level commands in this package.

**Comment by millejoh** [comment]
Nevermind - think I figured out how to fix the ecukes step.

**Comment by millejoh** [comment]
Looks like the dependency on `f` is coming from the testing code. Given that, `ein-pk.el` does not need to be updated. It's already in the Cask file, so no action needed I think. I'll look over the other commits and maybe cherrypick them into master, but it might be easier if you open a new PR focused just on improving testing robustness.

**Comment by millejoh** [comment]
As I am blind I did not see where the f- function was being used. But I do now. So consider this one merged. I had to adjust one of the test scenarios so don't think this will automatically close. I'll let this percolate a bit then manually close out this PR. As always, my thanks.

**Comment by dickmao** [comment]
Sorry, it was I who unknowingly introduced the `f.el` dependency.  I have a PR forthcoming to remove the dependency and also prevent future occurrences.

Thank you for applying `substitute-command-keys` for the ecukes tests and the defalias.

**Pull request closed without merging**
