### PR TITLE
Issue 630

### PR DESCRIPTION
**Pull request by millejoh**
Fix for #630.

### CODE REVIEW

**Comment by veprbl** [comment]
@millejoh I was just testing 0.16.2.3 and noticed that the bug is still present. Looking at the commit history I don't see the traces of this PR. Was it force pushed away?

**Comment by dickmao** [comment]
Did you look here?  v0.16.2.3 is a tag on the `old-master` branch.
https://github.com/millejoh/emacs-ipython-notebook/commits/v0.16.2.3

**Comment by veprbl** [comment]
@dickmao 
I see, thanks. Turns out, despite this PR being included, I still can reproduce #630 when using ein from the `v0.16.2.3` tag. Strangely enough, the issue is not seen on the current `master` (currently at 34e9ef39d161cc60d7cd823d9b2610dc0ad10ed9), where this PR is not included. Unfortunately I do observe #649 even on master and it breaks the undo functionality.

**Comment by dickmao** [comment]
Would appreciate if you can generate a minimum reproducible example (MRE) for #649, the scourge of EIN to be sure.  If you can follow the FAQ when you report the MRE, that would be ideal.

**Comment by veprbl** [comment]
See #670

**Pull request merged**
