### PR TITLE
Add multilang support for hy.

### PR DESCRIPTION
**Pull request by millejoh**
Maybe I should write a macro.

### CODE REVIEW

**Comment by tarsius** [comment]
What package defines `c++-mode`? As far as I can tell no package among the ~7400 on the Emacsmirror does.

**Comment by millejoh** [comment]
It's included with emacs (unless I'm missing something really obvious) - see cc-mode.el.

**Comment by tarsius** [comment]
Thanks for the information.

I wasn't aware that `cc-*.el` libraries use this non-standard macro instead of plain old `provide`:

```emacs-lisp
(defmacro cc-provide (feature)
  "A replacement for the `provide' form that restores the environment
after the compilation.  Don't use within `eval-when-compile'."
  `(progn
     (eval-when-compile (cc-bytecomp-restore-environment))
     (provide ,feature)))
```

I'll have to update my code to look for that too.

**Comment by tarsius** [comment]
Hm, actually its supposed to already detect that. Will have to investigate.
You're of the hook though. :wink:

**Comment by tarsius** [comment]
Ah... wrong again. I cannot see the feature `c++-mode` being provided anywhere in Emacs 27.0.60 (using `provide` or `cc-provide`).

**Comment by millejoh** [comment]
You are right, and unfortunately I am not off the hook. I should have wrote `(require cc-mode nil t)` instead of `(require c++-mode nil t)`. Thanks for catching this!

**Comment by tarsius** [comment]
Cheers!

**Pull request merged**
