### PR TITLE
Shutdown

### PR DESCRIPTION
**Pull request by dickmao**
On my linux machine and travis, I'm noticing the undocumented
`api/shutdown` does not reliably kill the server.

I tried my best with appveyor but couldn't coerce it back to the
working state 13 days ago.

### CODE REVIEW

**Comment by millejoh** [comment]
The api/shutdown does work on windows, or at least works better than the current solution, so why didn't you just make it's execution conditional on `system-type`? `delete-process` has a tendency to result in jupyter not exiting cleanly and leaving stale login token information on the system. This causes `ein:login` to fail mysteriously and unexpectedly. I'm not sure if the issue is jupyter, or windows, but all are out of scope of ein. This issue is [known](https://github.com/jupyter/notebook/issues/2844) and api/shutdown was proposed as a solution by the jupyter devs.

Make the call condition on system-type and see if you can at least get the unit and functional tests (excluding ecukes) working again on appveyor.

**Comment by dickmao** [comment]
> why didn't you just make it's [sic] execution conditional on system-type?

Once we have appveyor, this question might occur to me.  Currently I don't know what works better for windows, and I just try to get things to work for travis.  Whenever I see "(when (eq system-type 'windows-nt))" I leave it as-is.

[My run of master](https://ci.appveyor.com/project/dickmao/emacs-ipython-notebook) didn't pass the appveyor test.  This PR made some (perhaps ill-advised) changes to dislodge it to no avail.

**Comment by dickmao** [comment]
To be clear, this PR didn't elide the api/shutdown request.  It merely tacks on the old process-killing logic if it sees the api/shutdown didn't take.  It's a belt and suspenders thing.

**Comment by millejoh** [comment]
Ha. My bad, thought I saw a semicolon in there. Note that cask is installing to "/home/appveyor/.cask/bin", not "/msys64/home/appveyor/.cask".

The failure on your master certainly is an odd one. I'll have to do some more reading to understand what might be causing this. I did notice that your appveyor instance is using emacs 25, while mine is 26. I wonder if that is the difference, and if so then maybe the code should force a particular version.

**Pull request merged**
