### PR TITLE
Fix oinfo errors

### PR DESCRIPTION
**Pull request by millejoh**
Okay. @dickmao and @sam-s, if you guys are so inclined I could use some sanity checking on these commits. I think they will go some ways toward resolving the problems associated with #374. It should also make the company completion backend more robust and useful. 

As an added bonus try setting `ein:enable-eldoc-support` to `t`, open a notebook, make sure `eldoc-mode` is active and (I hope) enjoy the magic.

### CODE REVIEW

**Comment by dickmao** [comment]
I saw a "No module named ein" error when I logged into a remote server.  I made a test in #376 to replicate locally.

**Comment by millejoh** [comment]
Yes! Me too. That's because the remote python doesn't know how to find a file on the local machine. I just pushed another commit that should resolve that.

**Comment by millejoh** [comment]
The check failure appears to be because travis cannot find the pytools python file. This is the error:

```
(file-missing Opening input file No such file or directory /home/travis/build/millejoh/emacs-ipython-notebook/"foo"/ein_remote_safe.py)
```

What I don't understand is why there is a "foo" in the middle of the path. The code uses `ein:source-dir` which is just shorthand for `(file-name-directory load-file-name)`, called when `ein-core.el` is loaded. Is this an idiosyncrasy of travis? Do you have any ideas of how to work around this?

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/blob/fix-oinfo-errors/features/notebook.feature#L10

The idea is to test a scenario where the ein python files are missing.

**Comment by millejoh** [comment]
And, predictably, things fail when the python file is not around. EIN needs this glue code for the oinfo code to work. I could move the contents of `ein_remote_safe.py` into a big string inside of an el file, but keeping it separate makes development easier. Also since now I inject the code via a call to `ein:kernel-execute`, we no longer have the problem of remote python sessions unable to find the python file.

In a normal installation (i.e. downloading via melpa) I would expect everything except for zeroein.el to be installed. Do we really need to test for this scenario?

**Comment by dickmao** [comment]
I'm operating under the assumption that the`code` argument to `ein:kernel-execute` is something run remotely.  So if https://github.com/millejoh/emacs-ipython-notebook/blob/fix-oinfo-errors/lisp/ein-pytools.el#L66-L70 , then `ein_remote_safe.py` has to exist remotely?

**Pull request merged**
