### PR TITLE
This seems to be the culprit for #119

### LINKED ISSUE #119: Is emacs 25.x supported yet?
```
Debugger entered--Lisp error: (void-function cl-struct-define)
  cl-struct-define(undo-tree nil cl-structure-object nil nil ((cl-tag-slot) (root) (current) (size) (count) (object-pool)) cl-struct-undo-tree-tags cl-struct-undo-tree t)
  byte-code("\300\301\302\303#\210\304\305\306\307\306\211\310\311\312\303&	\207" [function-put make-undo-tree side-effect-free t cl-struct-define undo-tree nil cl-structure-object ((cl-tag-slot) (root) (current) (size) (count) (object-pool)) cl-struct-undo-tree-tags cl-struct-undo-tree] 10)
  require(undo-tree nil t)
  (and (require (quote undo-tree) nil t) (fboundp (quote global-undo-tree-mode)))
  (if (and (require (quote undo-tree) nil t) (fboundp (quote global-undo-tree-mode))) (progn (global-undo-tree-mode 1)))
  eval-buffer(#<buffer  *load*-263049> nil "/home/rob/.emacs.d/elpa/evil-20160827.1510/evil-integration.el" nil t)  ; Reading at buffer position 6235
  load-with-code-conversion("/home/rob/.emacs.d/elpa/evil-20160827.1510/evil-integration.el" "/home/rob/.emacs.d/elpa/evil-20160827.1510/evil-integration.el" nil t)
  require(evil-integration)
  eval-buffer(#<buffer  *load*-48499> nil "/home/rob/.emacs.d/elpa/evil-20160827.1510/evil.el" nil t)  ; Reading at buffer position 5267
  load-with-code-conversion("/home/rob/.emacs.d/elpa/evil-20160827.1510/evil.el" "/home/rob/.emacs.d/elpa/evil-20160827.1510/evil.el" nil t)
  require(evil)
  spacemacs-bootstrap/init-evil()
  funcall(spacemacs-bootstrap/init-evil)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (car (eieio-oref pkg (quote :owners))))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not ...) (spacemacs-buffer/message ...) (spacemacs-buffer/message ...) (condition-case err ... ...)))))) (eieio-oref pkg (quote :pre-layers))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-usedp layer) (progn (if (not ...) (spacemacs-buffer/message ...) (spacemacs-buffer/message ...) (condition-case err ... ...)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([object cfgl-package "evil" evil nil (spacemacs-bootstrap) nil (emacs-lisp ivy) elpa t bootstrap nil t nil])
  (cond ((eq (quote dotfile) (car (eieio-oref pkg (quote :owners)))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg t)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons ... load-path)) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq (quote local) location) (eq (quote dotfile) (car ...))) (setq load-path (cons (file-name-as-directory ...) load-path))) ((eq (quote local) location) (let* ((owner ...) (dir ...)) (setq load-path (cons ... load-path)))))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car (eieio-oref pkg (quote :owners)))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg t)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path ...) (configuration-layer//warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq ... location) (eq ... ...)) (setq load-path (cons ... load-path))) ((eq (quote local) location) (let* (... ...) (setq load-path ...))))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car (eieio-oref pkg ...))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg t)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location (eieio-oref pkg ...))) (cond ((stringp location) (if ... ... ...)) ((and ... ...) (setq load-path ...)) ((eq ... location) (let* ... ...)))) (if (memq (eieio-oref pkg (quote :location)) (quote (local site built-in))) nil (configuration-layer//activate-package pkg-name)) (cond ((eq (quote dotfile) (car ...)) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg ...))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owners))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (cfgl-package-enabledp pkg t)) (spacemacs-buffer/message (format "%S is toggled off." pkg-name))) (t (let ((location ...)) (cond (... ...) (... ...) (... ...))) (if (memq (eieio-oref pkg ...) (quote ...)) nil (configuration-layer//activate-package pkg-name)) (cond ((eq ... ...) (spacemacs-buffer/message ...)) (t (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((2048-game abbrev ac-ispell ace-jump-helm-line ace-link ace-window adaptive-wrap adoc-mode afternoon-theme aggressive-indent ahk-mode alchemist alect-themes alert ample-theme ample-zen-theme anaconda-mode ansi-colors ansible ansible-doc anti-zenburn-theme apropospriate-theme archive-mode arduino-mode async auctex auctex-latexmk auto-compile auto-complete auto-dictionary auto-highlight-symbol auto-yasnippet avy badwolf-theme biblio biblio-core bind-key bind-map birds-of-paradise-plus-theme bookmark bracketed-paste bubbleberry-theme bundler busybee-theme cargo cc-mode centered-buffer-mode centered-cursor cherry-blossom-theme chruby ...))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs-buffer/display-info-box) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/rob/.emacs.d/init.el" nil t)  ; Reading at buffer position 1194
  load-with-code-conversion("/home/rob/.emacs.d/init.el" "/home/rob/.emacs.d/init.el" t t)
  load("/home/rob/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
``` 

getting the above error when installing the package...

### PR DESCRIPTION
**Pull request by robbyoconnor**
Fixes #119

Also resolves syl20bnr/spacemacs#7181

### CODE REVIEW

**Comment by robbyoconnor** [comment]
CI faulure isn't my fault.

**Comment by millejoh** [comment]
Yeah, I know. EIN's test suite tries to mock up the IPython notebook behavior, but that behavior is mostly based on IPython v2.0. Add in a bunch of other bitrot issues and travis has been failing for quite some time.

I still don't fully understand why this is breaking on your installation and (apparently) on no one else's. I have a feeling, though, that no one really uses zeroein.el anymore so let us try merging in this change. If it ends up borking someone else's setup I am sure I will find out soon enough.

**Comment by robbyoconnor** [comment]
If it's anything...I was running Emacs 26 -- not sure if that does anything...

**Comment by millejoh** [comment]
That's interesting. I've also eliminated zeroein.el for the melpa recipe, so hopefully the transition to Emacs 26 will be much less bumpy for the rest of ein's users.

**Pull request merged**
